# Environment variables defined in a calling workflow are not accessible to this reusable workflow. Refer to the documentation for further details on this limitation.
name: build_pipelines_templates_build_extension_rider_public
on:
  workflow_call:
jobs:
  BuildRiderExtension:
    name: Build Rider Plugin
    runs-on: windows-latest
    env:
      pluginVersion: "${{ github.run_number }}"
    continue-on-error: true
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Install NuGet Tools
      uses: nuget/setup-nuget@v1.2.0
    - name: NuGet Restore
      run: nuget restore src/XamlStyler.Rider.sln -Verbosity Detailed -NonInteractive
    - name: Setup Java 16
      uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '16'
    - name: Build
      run: "./${{ runner.workspace }}\\s\\src\\XamlStyler.Extension.Rider\\gradlew.bat buildPlugin -PPluginVersion=${{ env.pluginVersion }}"
      working-directory: "${{ runner.workspace }}\\s\\src\\XamlStyler.Extension.Rider"
      env:
        GRADLE_OPTS: "-Xmx3072m"
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2.12.0
      if: always()
      with:
        junit_files: "**/TEST-*.xml"
    # The following script preserves the globbing behavior of the CopyFiles task.
    # Refer to this transformer's documentation for an alternative that will work in simple cases.
    - name: Copy Artifacts to Staging
      uses: actions/github-script@v7.0.0
      env:
        TARGET_FOLDER: "${{ runner.temp }}"
        CLEAN_TARGET_FOLDER: true
        FLATTEN_FOLDERS: true
        OVERWRITE: true
        CONTENTS: "${{ runner.workspace }}\\s\\src\\XamlStyler.Extension.Rider\\output\\**\\*.zip"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |-
          const fs = require('fs').promises
          const path = require('path')
          const target = path.resolve(process.env.TARGET_FOLDER)
          process.chdir(process.env.SOURCE_FOLDER || '.')
          if (process.env.CLEAN_TARGET_FOLDER === 'true') await io.rmRF(target)
          const flattenFolders = process.env.FLATTEN_FOLDERS === 'true'
          const options = {force: process.env.OVERWRITE === 'true'}
          const globber = await glob.create(process.env.CONTENTS || '**')
          for await (const file of globber.globGenerator()) {
            if ((await fs.lstat(file)).isDirectory()) continue
            const filename = flattenFolders ? path.basename(file) : file.substring(process.cwd().length)
            const dest = path.join(target, filename)
            await io.mkdirP(path.dirname(dest))
            await io.cp(file, dest, options)
          }
    - name: Publish artifacts
      uses: actions/upload-artifact@v4.1.0
      with:
        name: XamlStyler.Extension.Rider
