# Environment variables defined in a calling workflow are not accessible to this reusable workflow. Refer to the documentation for further details on this limitation.
name: build_pipelines_templates_run_tests_public
on:
  workflow_call:
jobs:
  RunUnitTests:
    name: Run Unit Tests
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    # The dotnet CLI does not accept glob patterns. Consider using a solution file to act on multiple projects at once.
    - name: Build
      run: dotnet build **/*UnitTests/*.csproj --configuration ${{ env.buildConfiguration }}
    # The dotnet CLI does not accept glob patterns. Consider using a solution file to act on multiple projects at once.
    - name: Run Tests
      run: dotnet test **/*UnitTests/*.csproj --logger trx --results-directory "${{ runner.temp }}" --configuration ${{ env.buildConfiguration }}
    - name: Run Tests
      uses: NasAmin/trx-parser@v0.5.0
      if: always()
      with:
        TRX_PATH: "${{ runner.temp }}"
        REPO_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
