name: CI

on:
  pull_request:
    branches:
    - master

env:
  env_buildConfiguration: Release
  env_major: 0
  env_patch: "$[counter(format('{0:yyMM}', pipeline.startTime), 0)]"

jobs:
  Variables:
    runs-on: ubuntu-latest
    outputs:
      buildConfiguration: ${{ env.env_buildConfiguration }}
      major: ${{ env.env_major }}
      patch: ${{ env.env_patch }}
    steps:
      - name: Echo
        if: false
        run: echo

  RunUnitTests:
    name: Run Unit Tests
    uses: "./.github/workflows/build_pipelines_templates_run_tests_public.yml"
  
  BuildExtension:
    name: Build VSIX
    uses: "./.github/workflows/build_pipelines_templates_build_extension_public.yml"
    with:
      test: test
  
  BuildConsoleNuget:
    name: Build NuGet Package
    uses: "./.github/workflows/build_pipelines_templates_build_console_public.yml"
  
  BuildRiderExtension:
    name: Build Rider Plugin
    uses: "./.github/workflows/build_pipelines_templates_build_extension_rider_public.yml"
