name: CI

on:
  pull_request:
    branches:
    - master

env:
  env_buildConfiguration: Release
  env_major: 0
  env_patch: "$[counter(format('{0:yyMM}', pipeline.startTime), 0)]"

jobs:
  RunUnitTests:
    name: Run Unit Tests
    uses: "./.github/workflows/build_pipelines_templates_run_tests_public.yml"
  
  BuildExtension:
    name: Build VSIX
    needs:
      - print
    uses: "./.github/workflows/build_pipelines_templates_build_extension_public.yml"
    with:
      buildConfiguration: ${{ needs.print.outputs.buildConfiguration }}
      major: ${{ needs.print.outputs.major }}
      patch: ${{ needs.print.outputs.patch }}
  
  BuildConsoleNuget:
    name: Build NuGet Package
    uses: "./.github/workflows/build_pipelines_templates_build_console_public.yml"
  
  BuildRiderExtension:
    name: Build Rider Plugin
    uses: "./.github/workflows/build_pipelines_templates_build_extension_rider_public.yml"
