name: CI

on:
  pull_request:
    branches:
    - master

env:
  env_buildConfiguration: Release
  env_major: 0
  env_patch: "$[counter(format('{0:yyMM}', pipeline.startTime), 0)]"

jobs:
  PrintVersion:
    runs-on: ubuntu-latest
    outputs:
      buildConfiguration: ${{ steps.step1.outputs.buildConfiguration }}
      major: ${{ steps.step1.outputs.major }}
      patch: ${{ steps.step1.outputs.patch }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: step1
        run: |
          echo "buildConfiguration=$buildConfiguration" >> $GITHUB_OUTPUT
          echo "major=$env_major" >> $GITHUB_OUTPUT
          echo "patch=$env_patch" >> $GITHUB_OUTPUT
          
  RunUnitTests:
    name: Run Unit Tests
    uses: "./.github/workflows/build_pipelines_templates_run_tests_public.yml"
  
  BuildExtension:
    name: Build VSIX
    uses: "./.github/workflows/build_pipelines_templates_build_extension_public.yml"
  
  BuildConsoleNuget:
    name: Build NuGet Package
    uses: "./.github/workflows/build_pipelines_templates_build_console_public.yml"
  
  BuildRiderExtension:
    name: Build Rider Plugin
    uses: "./.github/workflows/build_pipelines_templates_build_extension_rider_public.yml"
