name: CI

on:
  pull_request:
    branches:
    - master

env:
  env_buildConfiguration: Release
  env_major: 0
  env_patch: "$[counter(format('{0:yyMM}', pipeline.startTime), 0)]"

jobs:
  VersionString:
    runs-on: ubuntu-latest
    outputs:
      buildConfiguration: ${{ env.env_buildConfiguration }}
      version: ${{ env.env_major }}.${{ steps.minorStep.outputs.env_minor }}.${{ env.env_patch }}
    steps:
      - name: Get minor version number value
        id: minorStep
        run: |
          $minor=& Get-Date -format "yyMM"
          echo "env_minor=$minor" >> $GITHUB_OUTPUT

  RunUnitTests:
    name: Run Unit Tests
    uses: "./.github/workflows/build_pipelines_templates_run_tests_public.yml"
  
  BuildExtension:
    name: Build VSIX
    needs: VersionString
    uses: "./.github/workflows/build_pipelines_templates_build_extension_public.yml"
    with:
      buildConfiguration: release
      version: ${{ needs.VersionString.outputs.version }}
  
  BuildConsoleNuget:
    name: Build NuGet Package
    uses: "./.github/workflows/build_pipelines_templates_build_console_public.yml"
  
  BuildRiderExtension:
    name: Build Rider Plugin
    uses: "./.github/workflows/build_pipelines_templates_build_extension_rider_public.yml"
