name: CI

on:
  pull_request:
    branches:
    - master

env:
  env_buildConfiguration: Release
  env_major: 0

jobs:
  VersionString:
    runs-on: windows-latest
    outputs:
      buildConfiguration: ${{ env.env_buildConfiguration }}
      version: ${{ env.env_major }}.${{ env.env_minor }}.${{ github.run_number }}
    steps:
      - name: Get minor version number value
        run: |
          $NOW=& Get-Date -format "yyMM"
          echo "env_minor=$NOW" >> $env:GITHUB_ENV

  RunUnitTests:
    name: Run Unit Tests
    uses: "./.github/workflows/build_pipelines_templates_run_tests_public.yml"
  
  BuildExtension:
    name: Build VSIX
    needs: VersionString
    uses: "./.github/workflows/build_pipelines_templates_build_extension_public.yml"
    with:
      buildConfiguration: release
      version: ${{ needs.VersionString.outputs.version }}
  
  BuildConsoleNuget:
    name: Build NuGet Package
    uses: "./.github/workflows/build_pipelines_templates_build_console_public.yml"
  
  BuildRiderExtension:
    name: Build Rider Plugin
    uses: "./.github/workflows/build_pipelines_templates_build_extension_rider_public.yml"
