name: XAML%20Styler/CI
on:
  pull_request:
    branches:
    - master
env:
  buildConfiguration: Release
  major: 0
  patch: "$[counter(format('{0:yyMM}', pipeline.startTime), 0)]"
jobs:
  build_pipelines_templates_run_tests_public:
    name: build_pipelines_templates_run_tests_public
    uses: "./.github/workflows/build_pipelines_templates_run_tests_public.yml"
  build_pipelines_templates_build_extension_public:
    name: build_pipelines_templates_build_extension_public
    uses: "./.github/workflows/build_pipelines_templates_build_extension_public.yml"
  build_pipelines_templates_build_console_public:
    name: build_pipelines_templates_build_console_public
    uses: "./.github/workflows/build_pipelines_templates_build_console_public.yml"
  build_pipelines_templates_build_extension_rider_public:
    name: build_pipelines_templates_build_extension_rider_public
    uses: "./.github/workflows/build_pipelines_templates_build_extension_rider_public.yml"
